var myString;
var myNum;
var myBool;
var myVar;
var strArray;
var numArray;
var anotherArray;
var strNumTuple;
var myVoid = undefined;
var myNull = null;
var myUndefine = null;
myString = "Hello World";
myNum = 22;
myBool = true;
myVar: 22;
strArray = ["a", "b", "c"];
anotherArray = ["d", "e", "f"];
numArray = [1, 2, 3, 4, 5];
strNumTuple = ["a", 5];
console.log(myString);
